# collection of functions for reading satellite data
#

import earthaccess
import os
import xarray as xr
import numpy as np

def test_print():

    print(" Holy crap ... it worked!  Didn't it?!? ")


# general routine to open a data file
#
def open_data_file(ifile,level='L2',loc='cloud'):
    
    if 'cloud' in loc:
        path = earthaccess.open(ifile)
        ifile = path[0]
        dataset = xr.open_dataset(ifile)
    else:
        dataset = xr.open_dataset(ifile)

    if 'L2' in level:
        datatree = xr.open_datatree(ifile)
        dataset = xr.merge(datatree.to_dict().values())

    return dataset


def open_data(ifile):

    loc = 'local'
    typ = 'L2'
    
    if isinstance(ifile, list):
        if isinstance(ifile[0], earthaccess.results.DataGranule):
            loc = 'cloud'
            if 'L3' in ifile[0].data_links()[0]: level = 'L3'
    else:
        if 'L3' in ifile: level = 'L3'
            
    dataset = open_data_file(ifile,level=typ,loc=loc)

    return dataset



# Carina and Anna's routine to write an OCSSW parameter file
#
def write_par(path, par):
    """Prepare a parameter file to be read by one of the OCSSW tools.

    Using a parameter file (a.k.a. "par file") is equivalent to specifying
    parameters on the command line.

    Parameters
    ----------
    path
        where to write the parameter file
    par
        the parameter names and values included in the file

    Example
    -------
par = {
    "ifile": l1b_path,
    "ofile": data / l1b_name.replace("L1B", "L2"),
    "north": 39,
    "south": 35,
    "west": -76,
    "east": -74.5,
    "l2prod": "Rrs",
    "proc_uncertainty": 0,
}
write_par("l2gen.par", par)
        
    """
    with open(path, "w") as file:
        writer = csv.writer(file, delimiter="=")
        writer.writerows(par.items())


# functions to remind myself what data is available via earthaccess
#
def list_avail_oci():
    results = earthaccess.search_datasets(instrument="oci")
    for item in results:
        summary = item.summary()
        print(summary["short-name"])

def list_avail_harp2():
    results = earthaccess.search_datasets(instrument="harp2")
    for item in results:
        summary = item.summary()
        print(summary["short-name"])

def list_avail_spexone():
    results = earthaccess.search_datasets(instrument="spexone")
    for item in results:
        summary = item.summary()
        print(summary["short-name"])

        
# add a swath outline to a L2 image
# generated by chatGSFC while at the 2025 Hack
#
def add_swath_outline(ax, dataset, data_var, outline_color='black', linewidth=1):
    """Add swath outline to existing plot."""
    
    # Get coordinates
    lon_coords = dataset.longitude.values
    lat_coords = dataset.latitude.values
    data_values = data_var.values
    
    # Handle different coordinate structures
    if lon_coords.ndim == 2 and lat_coords.ndim == 2:
        # Curvilinear grid - use perimeter
        rows, cols = lon_coords.shape
        
        # Extract perimeter
        perimeter_lons = np.concatenate([
            lon_coords[0, :],           # top
            lon_coords[1:, -1],         # right
            lon_coords[-1, :-1][::-1],  # bottom (reversed)
            lon_coords[:-1, 0][::-1]    # left (reversed)
        ])
        
        perimeter_lats = np.concatenate([
            lat_coords[0, :],           # top
            lat_coords[1:, -1],         # right
            lat_coords[-1, :-1][::-1],  # bottom (reversed)
            lat_coords[:-1, 0][::-1]    # left (reversed)
        ])
        
        # Close polygon
        perimeter_lons = np.append(perimeter_lons, perimeter_lons[0])
        perimeter_lats = np.append(perimeter_lats, perimeter_lats[0])
        
    else:
        # Regular grid - use bounding box
        lon_min, lon_max = lon_coords.min(), lon_coords.max()
        lat_min, lat_max = lat_coords.min(), lat_coords.max()
        perimeter_lons = [lon_min, lon_max, lon_max, lon_min, lon_min]
        perimeter_lats = [lat_min, lat_min, lat_max, lat_max, lat_min]
    
    # Draw outline
    ax.plot(perimeter_lons, perimeter_lats, color=outline_color, 
            linewidth=linewidth, label='Swath Outline', linestyle=":")
    #ax.legend()
